# Anthropic Provider Configuration
# Version: 1.0.0

endpoint = "https://api.anthropic.com/v1"
models = []
models_path = "/models"
chat_path = "/messages"

[headers]
anthropic-version = "2023-06-01"
x-api-key = "${api_key}"

[vars]

[chat_templates."claude.*"]
request = """
{
  "model": "{{ model }}",
  "messages": {{ messages | base_messages | json }}{% if max_tokens %},
  "max_tokens": {{ max_tokens }}{% endif %}{% if temperature %},
  "temperature": {{ temperature }}{% endif %}{% if system_prompt %},
  "system": "{{ system_prompt }}"{% endif %}{% if stream %},
  "stream": {{ stream }}{% endif %}
}
"""

response = """
{
  "content": {% if content and content[0] and content[0].text %}"{{ content[0].text | replace(from='"', to='\\"') }}"{% else %}"No response content available."{% endif %}
}
"""