# Anthropic Provider Configuration
# Version: 1.0.0

endpoint = "https://api.anthropic.com/v1"
models = []
models_path = "/models"
chat_path = "/messages"
embeddings_path = "/embeddings"

[headers]
anthropic-version = "2023-06-01"
x-api-key = "${api_key}"

[vars]

[chat_templates."claude.*"]
request = """
{
  "model": "{{ model }}",
  "messages": {{ messages | anthropic_messages | json }}{% if max_tokens %},
  "max_tokens": {{ max_tokens }}{% endif %}{% if temperature %},
  "temperature": {{ temperature }}{% endif %}{% if system_prompt %},
  "system": "{{ system_prompt }}"{% endif %}{% if stream %},
  "stream": {{ stream }}{% endif %}
}
"""

response = """
{
  "content": {% if content and content[0] and content[0].text %}{{ content[0].text | json }}{% else %}"No response content available."{% endif %}
}
"""

# Embeddings endpoint templates (Note: Anthropic doesn't provide embeddings models)
[embeddings_templates.""]
request = """
{
  "model": "{{ model }}",
  "input": "{{ input }}"
}
"""
response = """
{
  "data": [
    {
      "embedding": {{ data[0].embedding | json }}
    }
  ]
}
"""