endpoint = "https://api.llama.com/v1"
models = []
models_path = "/models"
chat_path = "/chat/completions"

[headers]

[vars]

[chat_templates.""]
response = '''
{
  "content": {{ completion_message.content.text | json }}
}
'''
