endpoint = "https://us-east5-aiplatform.googleapis.com"
models = []
models_path = "/models"
chat_path = "/v1/projects/{project}/locations/{location}/endpoints/openapi/chat/completions"
token_url = "https://oauth2.googleapis.com/token"
auth_type = "google_sa_jwt"

[headers]

# change this directly
# or do 
# lc providers vars set vertex_google project your-actual-gcp-project-id
# lc providers vars set location us-east5
[vars]
location = "your-actual-gcp-project-location" 
project = "your-actual-gcp-project-id"